{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dalikamata.fullname" . }}-prometheus-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dalikamata.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
  {{- with .Values.prometheus.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
