apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dalikamata.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dalikamata.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dalikamata.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  template:
    metadata:
      labels:
        {{- include "dalikamata.labels" . | nindent 8 }}
        app.kubernetes.io/component: metrics
    spec:
      containers:
        - name: metrics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--nats-host={{ include "dalikamata.natsServiceName" . }}"
            - "--nats-port={{ .Values.nats.port }}"
            - "--metrics-addr=0.0.0.0:{{ .Values.metrics.port }}"
            - "metrics"
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 15
