FROM grafana/grafana:latest

USER root
RUN grafana-cli --pluginsDir /var/lib/grafana/plugins plugins install yesoreyeram-infinity-datasource
COPY --chown=grafana:grafana deploy/docker/grafana_provisioning /etc/grafana/provisioning
USER grafana
