services:
  dalikamata-nats:
    image: dalikamata:latest
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    command:
      - "nats"
    ports:
      - "4222:4222"
    networks:
      - monitoring

  dalikamata:
    image: dalikamata:latest
    command:
      - "--nats-host=dalikamata-nats"
      - "domain"
    depends_on:
      - dalikamata-nats
    networks:
      - monitoring

  dalikamata-fake-bitbucket:
    image: dalifakes:latest
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.fakes
    command:
      - "bitbucket"
      - "--addr=0.0.0.0:7990"
    ports:
      - "7990:7990"
    networks:
      - monitoring

  dalikamata-ingest-bitbucket:
    image: dalikamata:latest
    command:
      - "--bitbucket-url=http://dalikamata-fake-bitbucket:7990"
      - "--bitbucket-token=x"
      - "--bitbucket-projects=PROJ,INFR"
      - "--nats-host=dalikamata-nats"
      - "ingest"
      - "bitbucket"
    depends_on:
      - dalikamata-fake-bitbucket
      - dalikamata
    networks:
      - monitoring

  dalikamata-metrics:
    image: dalikamata:latest
    command:
      - "--nats-host=dalikamata-nats"
      - "metrics"
      - "--debug"
    depends_on:
      - dalikamata
    ports:
      - "2112:2112"
    networks:
      - monitoring

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-micro.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_DISABLE_INITIAL_ADMIN_CREATION=false
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_storage:
