services:
  dalikamata:
    image: dalikamata:latest
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    command: ["domain"]
    ports:
      - "4222:4222"
      - "2112:2112"
    networks:
      - monitoring

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_DISABLE_INITIAL_ADMIN_CREATION=false
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning/datasources
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_storage:
