services:
  dalikamata-fake-bitbucket:
    image: dalifakes:latest
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.fakes
    command:
      - "bitbucket"
      - "--addr=0.0.0.0:27990"
    ports:
      - "27990:27990"

  dalikamata-nats:
    image: dalikamata:latest
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    command:
      - "--nats-port=24222"
      - "nats"
      - "--nats-data=/tmp/nats"
    ports:
      - "24222:24222"

  dalikamata-domain:
    image: dalikamata:latest
    command:
      - "--nats-host=dalikamata-nats"
      - "--nats-port=24222"
      - "domain"
    depends_on:
      - dalikamata-nats

  dalikamata-metrics:
    image: dalikamata:latest
    command:
      - "--nats-host=dalikamata-nats"
      - "--nats-port=24222"
      - "--metrics-addr=0.0.0.0:22112"
      - "metrics"
    depends_on:
      - dalikamata-nats
    ports:
      - "22112:22112"

  dalikamata-ingest:
    image: dalikamata:latest
    command:
      - "--nats-host=dalikamata-nats"
      - "--nats-port=24222"
      - "ingest"
      - "bitbucket"
      - "--bitbucket-url=http://dalikamata-fake-bitbucket:27990"
      - "--bitbucket-token=test-token"
      - "--bitbucket-projects=PROJ,INFRA"
    depends_on:
      - dalikamata-fake-bitbucket
      - dalikamata-domain

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles: ["monitoring"]
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-micro.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles: ["monitoring"]
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_DISABLE_INITIAL_ADMIN_CREATION=false
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
      - grafana_storage:/var/lib/grafana

volumes:
 grafana_storage:
