apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Dalikamata API
    uid: dalikamata-api
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: ${DALIKAMATA_API_URL}
