{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dalikamata.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dalikamata.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "dalikamata.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: api
      port: {{ .Values.api.port }}
      targetPort: api
      protocol: TCP
{{- end }}
