{{- if .Values.domain.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dalikamata.fullname" . }}-domain
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dalikamata.labels" . | nindent 4 }}
    app.kubernetes.io/component: domain
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dalikamata.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: domain
  template:
    metadata:
      labels:
        {{- include "dalikamata.labels" . | nindent 8 }}
        app.kubernetes.io/component: domain
    spec:
      containers:
        - name: domain
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--nats-host={{ include "dalikamata.natsServiceName" . }}"
            - "--nats-port={{ .Values.nats.port }}"
            - "domain"
{{- end }}
