{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dalikamata.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dalikamata.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    {{- include "dalikamata.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
{{- end }}
