{{- if .Values.ingest.bitbucket.url }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dalikamata.fullname" . }}-ingest-bitbucket
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dalikamata.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest-bitbucket
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dalikamata.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingest-bitbucket
  template:
    metadata:
      labels:
        {{- include "dalikamata.labels" . | nindent 8 }}
        app.kubernetes.io/component: ingest-bitbucket
    spec:
      containers:
        - name: ingest-bitbucket
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--nats-host={{ include "dalikamata.natsServiceName" . }}"
            - "--nats-port={{ .Values.nats.port }}"
            - "ingest"
            - "bitbucket"
            - "--bitbucket-url={{ .Values.ingest.bitbucket.url }}"
            - "--bitbucket-token=$(BITBUCKET_TOKEN)"
            - "--bitbucket-projects={{ required "ingest.bitbucket.projects is required" .Values.ingest.bitbucket.projects }}"
            {{- if .Values.ingest.bitbucket.caCertsDir }}
            - "--ca-certs-dir={{ .Values.ingest.bitbucket.caCertsDir }}"
            {{- end }}
            {{- if .Values.ingest.bitbucket.componentConfig.enabled }}
            - "--bitbucket-component-config-enabled"
            - "--bitbucket-component-config-file={{ .Values.ingest.bitbucket.componentConfig.file }}"
            {{- end }}
            {{- if .Values.ingest.bitbucket.debug }}
            - "--debug"
            {{- end }}
          env:
            - name: BITBUCKET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "dalikamata.bitbucketSecretName" . }}
                  key: token
          {{- with .Values.ingest.bitbucket.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ingest.bitbucket.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
